let languages = [
  {text: 'Afrikaans', value: 'afr'},
  {text: 'Amharic', value: 'amh'},
  {text: 'Arabic', value: 'ara'},
  {text: 'Assamese', value: 'asm'},
  {text: 'Azerbaijani', value: 'aze'},
  {text: 'Azerbaijani - Cyrillic', value: 'aze_cyrl'},
  {text: 'Belarusian', value: 'bel'},
  {text: 'Bengali', value: 'ben'},
  {text: 'Tibetan', value: 'bod'},
  {text: 'Bosnian', value: 'bos'},
  {text: 'Bulgarian', value: 'bul'},
  {text: 'Catalan; Valencian', value: 'cat'},
  {text: 'Cebuano', value: 'ceb'},
  {text: 'Czech', value: 'ces'},
  {text: 'Chinese - Simplified', value: 'chi_sim'},
  {text: 'Chinese - Traditional', value: 'chi_tra'},
  {text: 'Cherokee', value: 'chr'},
  {text: 'Welsh', value: 'cym'},
  {text: 'Danish', value: 'dan'},
  {text: 'German', value: 'deu'},
  {text: 'Dzongkha', value: 'dzo'},
  {text: 'Greek, Modern (1453-)', value: 'ell'},
  {text: 'English', value: 'eng'},
  {text: 'English, Middle (1100-1500)', value: 'enm'},
  {text: 'Esperanto', value: 'epo'},
  {text: 'Estonian', value: 'est'},
  {text: 'Basque', value: 'eus'},
  {text: 'Persian', value: 'fas'},
  {text: 'Finnish', value: 'fin'},
  {text: 'French', value: 'fra'},
  {text: 'German Fraktur', value: 'frk'},
  {text: 'French, Middle (ca. 1400-1600)', value: 'frm'},
  {text: 'Irish', value: 'gle'},
  {text: 'Galician', value: 'glg'},
  {text: 'Greek, Ancient (-1453)', value: 'grc'},
  {text: 'Gujarati', value: 'guj'},
  {text: 'Haitian; Haitian Creole', value: 'hat'},
  {text: 'Hebrew', value: 'heb'},
  {text: 'Hindi', value: 'hin'},
  {text: 'Croatian', value: 'hrv'},
  {text: 'Hungarian', value: 'hun'},
  {text: 'Inuktitut', value: 'iku'},
  {text: 'Indonesian', value: 'ind'},
  {text: 'Icelandic', value: 'isl'},
  {text: 'Italian', value: 'ita'},
  {text: 'Italian - Old', value: 'ita_old'},
  {text: 'Javanese', value: 'jav'},
  {text: 'Japanese', value: 'jpn'},
  {text: 'Kannada', value: 'kan'},
  {text: 'Georgian', value: 'kat'},
  {text: 'Georgian - Old', value: 'kat_old'},
  {text: 'Kazakh', value: 'kaz'},
  {text: 'Central Khmer', value: 'khm'},
  {text: 'Kirghiz; Kyrgyz', value: 'kir'},
  {text: 'Korean', value: 'kor'},
  {text: 'Kurdish', value: 'kur'},
  {text: 'Lao', value: 'lao'},
  {text: 'Latin', value: 'lat'},
  {text: 'Latvian', value: 'lav'},
  {text: 'Lithuanian', value: 'lit'},
  {text: 'Malayalam', value: 'mal'},
  {text: 'Marathi', value: 'mar'},
  {text: 'Macedonian', value: 'mkd'},
  {text: 'Maltese', value: 'mlt'},
  {text: 'Malay', value: 'msa'},
  {text: 'Burmese', value: 'mya'},
  {text: 'Nepali', value: 'nep'},
  {text: 'Dutch; Flemish', value: 'nld'},
  {text: 'Norwegian', value: 'nor'},
  {text: 'Oriya', value: 'ori'},
  {text: 'Panjabi; Punjabi', value: 'pan'},
  {text: 'Polish', value: 'pol'},
  {text: 'Portuguese', value: 'por'},
  {text: 'Pushto; Pashto', value: 'pus'},
  {text: 'Romanian; Moldavian; Moldovan', value: 'ron'},
  {text: 'Russian', value: 'rus'},
  {text: 'Sanskrit', value: 'san'},
  {text: 'Sinhala; Sinhalese', value: 'sin'},
  {text: 'Slovak', value: 'slk'},
  {text: 'Slovenian', value: 'slv'},
  {text: 'Spanish; Castilian', value: 'spa'},
  {text: 'Spanish; Castilian - Old', value: 'spa_old'},
  {text: 'Albanian', value: 'sqi'},
  {text: 'Serbian', value: 'srp'},
  {text: 'Serbian - Latin', value: 'srp_latn'},
  {text: 'Swahili', value: 'swa'},
  {text: 'Swedish', value: 'swe'},
  {text: 'Syriac', value: 'syr'},
  {text: 'Tamil', value: 'tam'},
  {text: 'Telugu', value: 'tel'},
  {text: 'Tajik', value: 'tgk'},
  {text: 'Tagalog', value: 'tgl'},
  {text: 'Thai', value: 'tha'},
  {text: 'Tigrinya', value: 'tir'},
  {text: 'Turkish', value: 'tur'},
  {text: 'Uighur; Uyghur', value: 'uig'},
  {text: 'Ukrainian', value: 'ukr'},
  {text: 'Urdu', value: 'urd'},
  {text: 'Uzbek', value: 'uzb'},
  {text: 'Uzbek - Cyrillic', value: 'uzb_cyrl'},
  {text: 'Vietnamese', value: 'vie'},
  {text: 'Yiddish', value: 'yid'},
].sort(function(a, b) {
  let x = a.text.toLowerCase();
  let y = b.text.toLowerCase();
  return x < y ? -1 : x > y ? 1 : 0;
});

var TesseractConfig = {
  'languages': languages,
};